=== garyg1/gantt-chart-tool/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Gantt Chart Tool schema.",
    "type": "object",
    "properties": {
        "title": {
            "type": "string",
            "description": "Title displayed in the rendered chart."
        },
        "config": {
            "type": "object",
            "properties": {
                "dateLabels": {
                    "type": "boolean",
                    "description": "Whether to show date labels in the rendered chart."
                },
                "showDeps": {
                    "type": "boolean",
                    "description": "Whether to render lines between dependent tasks."
                },
                "width": {
                    "type": "number",
                    "description": "Width (pixels) of the rendered chart."
                },
                "font": {
                    "type": "string",
                    "description": "Font family used in the rendered chart."
                },
                "googleFont": {
                    "type": "string",
                    "description": "Google font name (https://fonts.google.com) to use in the rendered chart. Note this will trigger a request to the Google Fonts service containing the name typed here."
                },
                "palette": {
                    "type": "object",
                    "properties": {
                        "gradient": {
                            "description": "Colors the chart by a gradient between two colors. The swimlanes will be colored [gradient[0], blend1, blend2, ..., blendN, gradient[1]].",
                            "type": "array",
                            "items": {
                                "type": "string",
                                "format": "color"
                            }
                        },
                        "stripes": {
                            "description": "Options for stripes in background of rendered chart.",
                            "type": "object",
                            "properties": {
                                "size": {
                                    "type": "number",
                                    "description": "Size (in pixels) of the stripes."
                                },
                                "strength": {
                                    "type": "number",
                                    "description": "Opacity (max 1.0) of the stripes."
                                }
                            }
                        },
                        "gridColor": {
                            "type": "string",
                            "format": "color",
                            "description": "Color of the x-axis grid lines in the background."
                        }
                    },
                    "required": ["gradient"]
                },
                "startDate": {
                    "type": "string",
                    "format": "date",
                    "description": "The start date to use when auto-scheduling tasks. No task will be scheduled before this date."
                }
            },
            "required": []
        },
        "swimlanes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string",
                        "description": "A unique ID for the swimlane."
                    },
                    "name": {
                        "type": "string",
                        "description": "The displayed name of the swimlane."
                    },
                    "maxParallelism": {
                        "type": "number",
                        "description": "The maximum number of tasks that can be scheduled in parallel for this swimlane."
                    },
                    "hidden": {
                        "type": "boolean",
                        "description": "Whether to show this swimlane in the rendered chart."
                    },
                    "color": {
                        "type": "string",
                        "format": "color",
                        "description": "Overrides the color for this swimlane."
                    }
                },
                "required": ["id", "name"]
            }
        },
        "tasks": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The displayed name and key for the task"
                    },
                    "swimlaneId": {
                        "type": "string",
                        "description": "The swimlane.id for the task."
                    },
                    "duration": {
                        "type": "string",
                        "format": "duration",
                        "description": "Duration for the task, if auto-scheduled."
                    },
                    "deps": {
                        "type": "array",
                        "description": "A list of task names that must be executed before this task.",
                        "items": { "type": "string" }
                    },
                    "width": {
                        "type": "number",
                        "description": "The amount of 'bandwidth' this task takes up. For example, if `swimlane.maxParallelism = 3`, and `task.width = 3`, then this task will block the entire swimlane until it finishes executing.",
                        "default": 1
                    },
                    "interval": {
                        "type": "object",
                        "description": "The start and end times for this task, if not auto-scheduled.",
                        "properties": {
                            "start": {
                                "type": "string",
                                "format": "date"
                            },
                            "end": { "type": "string", "format": "date" }
                        },
                        "required": ["start", "end"]
                    }
                },
                "anyOf": [
                    { "required": ["interval"] },
                    { "required": ["duration"] }
                ],
                "required": ["name", "swimlaneId"]
            }
        }
    },
    "required": ["title", "config", "swimlanes", "tasks"]
}

=== garyg1/gantt-chart-tool/docs/examples/Basic-Example.json
{
    "title": "Project A",
    "config": {
        "width": 750,
        "googleFont": "Atkinson Hyperlegible",
        "startDate": "2024-11-10",
        "palette": {
            "gradient": ["#3c5ca2", "seagreen", "#eee"],
            "stripes": { "size": 6, "strength": 0.15 }
        },
        "padding": { "swimlanes": 10, "dateScale": 15 },
        "fontSizes": { "title": 29 },
        "gridTicks": 5
    },
    "swimlanes": [
        { "id": "1", "name": "A", "maxParallelism": 2 },
        { "id": "2", "name": "B", "maxParallelism": 2 },
        { "id": "3", "name": "C", "maxParallelism": 1, "hidden": false },
        { "id": "4", "name": "D", "maxParallelism": 1 },
        { "id": "5", "name": "E", "maxParallelism": 2 }
    ],
    "tasks": [
        {
            "name": "Task 1",
            "swimlaneId": "1",
            "duration": "P10D",
            "deps": [],
            "width": 1
        },
        {
            "name": "Task 2",
            "swimlaneId": "2",
            "duration": "P21D",
            "deps": ["Task 1"]
        },
        {
            "name": "Task 3",
            "swimlaneId": "3",
            "duration": "P22D",
            "deps": ["Task 2"]
        },
        {
            "name": "Task 4",
            "swimlaneId": "4",
            "duration": "P22D",
            "deps": ["Task 3"]
        },
        {
            "name": "Task 5",
            "swimlaneId": "5",
            "duration": "P24D",
            "deps": ["Task 4"],
            "width": 1
        },
        {
            "name": "Task 6",
            "swimlaneId": "4",
            "duration": "P23D",
            "deps": ["Task 4"],
            "width": 1
        },
        {
            "name": "Task 7",
            "swimlaneId": "1",
            "duration": "P12D",
            "deps": ["Task 1"],
            "width": 1
        },
        {
            "name": "Task 8",
            "swimlaneId": "1",
            "duration": "P11D",
            "deps": []
        },
        {
            "name": "Task 9",
            "swimlaneId": "2",
            "duration": "P22D",
            "deps": ["Task 8"],
            "width": 1
        },
        {
            "name": "Task 10",
            "swimlaneId": "5",
            "duration": "P33D",
            "deps": ["Task 9"]
        },
        {
            "name": "Task 11",
            "swimlaneId": "1",
            "duration": "P24D",
            "deps": []
        },
        {
            "name": "Task 12",
            "swimlaneId": "1",
            "duration": "P21D",
            "deps": ["Task 11", "Task 8"]
        },
        {
            "name": "Task 13",
            "swimlaneId": "5",
            "duration": "P15D",
            "deps": []
        },
        {
            "name": "Task 14",
            "swimlaneId": "2",
            "duration": "P14D",
            "deps": ["Task 12"]
        },
        {
            "name": "Fixed Task A",
            "swimlaneId": "1",
            "interval": { "start": "2024-12-22", "end": "2025-01-31" }
        },
        {
            "name": "Fixed Task B",
            "swimlaneId": "2",
            "interval": { "start": "2024-11-27", "end": "2024-12-04" }
        }
    ]
}

=== garyg1/gantt-chart-tool/docs/examples/Colorful-Example.json
{
    "title": "Project A",
    "config": {
        "width": 800,
        "googleFont": "Atkinson Hyperlegible",
        "startDate": "2024-11-10",
        "palette": {
            "gradient": ["#c5b246", "#b72a2a"],
            "backgroundColor": "#1d3251",
            "gridColor": "#293c58",
            "stripes": { "size": 10, "strength": 0.05 },
            "outlines": { "thresholdL1": 0 }
        },
        "padding": {
            "tasks": 6,
            "taskHeight": 15,
            "swimlanes": 20,
            "chartX": 60,
            "chartY": 60
        },
        "fontSizes": { "taskNames": 12, "taskDates": 12, "title": 20 }
    },
    "swimlanes": [
        { "id": "1", "name": "A", "maxParallelism": 3 },
        { "id": "2", "name": "B", "maxParallelism": 1 },
        { "id": "3", "name": "C", "maxParallelism": 1, "hidden": false },
        { "id": "4", "name": "D", "maxParallelism": 1 },
        { "id": "5", "name": "E", "maxParallelism": 2 }
    ],
    "tasks": [
        {
            "name": "Task 1",
            "swimlaneId": "1",
            "duration": "PT23D",
            "deps": []
        },
        {
            "name": "Task 2",
            "swimlaneId": "2",
            "duration": "PT20D",
            "deps": ["Task 1"]
        },
        {
            "name": "Task 3",
            "swimlaneId": "3",
            "duration": "PT19D",
            "deps": ["Task 2"]
        },
        {
            "name": "Task 4",
            "swimlaneId": "4",
            "duration": "PT21D",
            "deps": ["Task 3"]
        },
        {
            "name": "Task 5",
            "swimlaneId": "5",
            "duration": "PT12D",
            "deps": ["Task 4"]
        },
        {
            "name": "Task 6",
            "swimlaneId": "2",
            "duration": "PT23D",
            "deps": ["Task 1"],
            "width": 1
        },
        {
            "name": "Task 7",
            "swimlaneId": "5",
            "duration": "PT13D",
            "deps": ["Task 5", "Task 2"]
        },
        {
            "name": "Task 8",
            "swimlaneId": "1",
            "duration": "PT12D",
            "deps": []
        },
        {
            "name": "Task 9",
            "swimlaneId": "2",
            "duration": "PT15D",
            "deps": ["Task 8"],
            "width": 1
        },
        {
            "name": "Task 10",
            "swimlaneId": "5",
            "duration": "PT22D",
            "deps": ["Task 9"]
        },
        {
            "name": "Task 11",
            "swimlaneId": "5",
            "duration": "PT18D",
            "deps": ["Task 9"],
            "width": 1
        },
        {
            "name": "Task 12",
            "swimlaneId": "1",
            "duration": "PT17D",
            "deps": ["Task 10"]
        },
        {
            "name": "Task 13",
            "swimlaneId": "1",
            "duration": "PT23D",
            "deps": ["Task 8"]
        },
        {
            "name": "Task 14",
            "swimlaneId": "4",
            "duration": "PT24D",
            "deps": ["Task 9"]
        },
        {
            "name": "Fixed Task A",
            "swimlaneId": "1",
            "interval": { "start": "2024-12-12", "end": "2024-12-31" }
        },
        {
            "name": "Fixed Task B",
            "swimlaneId": "2",
            "interval": { "start": "2024-12-28", "end": "2025-01-25" }
        }
    ]
}

=== garyg1/gantt-chart-tool/docs/examples/Example-Completed-Tasks.json
{
    "title": "Project A",
    "config": {
        "width": 800,
        "font": "Space Grotesk",
        "startDate": "2024-12-05",
        "dateLabels": true,
        "showDeps": false,
        "palette": {
            "gradient": ["#3c5ca2", "seagreen", "#eee"],
            "backgroundColor": "black",
            "stripes": { "size": 6, "strength": 0.15 },
            "outlines": { "thresholdL1": 210, "strength": 0.25 }
        },
        "padding": {
            "tasks": 5,
            "taskHeight": 15,
            "swimlanes": 5,
            "chartX": 10,
            "chartY": 5
        },
        "fontSizes": { "taskNames": 12, "taskDates": 10, "title": 22 }
    },
    "swimlanes": [
        { "id": "1", "name": "A", "maxParallelism": 3 },
        { "id": "2", "name": "B", "maxParallelism": 2 },
        { "id": "3", "name": "C", "maxParallelism": 1, "hidden": false },
        { "id": "4", "name": "D", "maxParallelism": 1 },
        { "id": "5", "name": "E", "maxParallelism": 2 }
    ],
    "tasks": [
        {
            "name": "Task 1",
            "swimlaneId": "1",
            "duration": "P24D",
            "deps": [],
            "completed": true
        },
        {
            "name": "Task 2",
            "swimlaneId": "1",
            "duration": "P2W",
            "deps": ["Task 1"]
        },
        {
            "name": "Task 3",
            "swimlaneId": "1",
            "duration": "P24D",
            "deps": ["Task 2"]
        },
        {
            "name": "Task 4",
            "swimlaneId": "2",
            "duration": "P15D",
            "deps": ["Task 3"],
            "width": 1
        },
        {
            "name": "Task 5",
            "swimlaneId": "1",
            "duration": "P20D",
            "deps": [],
            "width": 1,
            "completed": true
        },
        {
            "name": "Task 6",
            "swimlaneId": "2",
            "duration": "P2W",
            "deps": ["Task 5"],
            "width": 1
        },
        {
            "name": "Task 7",
            "swimlaneId": "3",
            "duration": "P18D",
            "deps": ["Task 6"]
        },
        {
            "name": "Task 8",
            "swimlaneId": "4",
            "duration": "P11D",
            "deps": ["Task 7"]
        },
        {
            "name": "Task 9",
            "swimlaneId": "5",
            "duration": "P17D",
            "deps": ["Task 8"]
        },
        {
            "name": "Task 10",
            "swimlaneId": "3",
            "duration": "P3W",
            "deps": []
        },
        {
            "name": "Task 11",
            "swimlaneId": "5",
            "duration": "P15D",
            "deps": []
        },
        {
            "name": "Task 12",
            "swimlaneId": "2",
            "duration": "P18D",
            "deps": ["Task 6"]
        },
        {
            "name": "Task 13",
            "swimlaneId": "1",
            "duration": "P17D",
            "deps": ["Task 6"]
        },
        {
            "name": "Task 14",
            "swimlaneId": "1",
            "duration": "P15D",
            "deps": ["Task 5"]
        },
        {
            "name": "Task 15",
            "swimlaneId": "1",
            "duration": "P2W",
            "deps": ["Task 7"],
            "width": 1
        },
        {
            "name": "Task 16",
            "swimlaneId": "3",
            "duration": "P2W",
            "deps": ["Task 7"]
        },
        {
            "name": "Fixed Task A",
            "swimlaneId": "1",
            "interval": { "start": "2024-12-07", "end": "2025-01-19" }
        },
        {
            "name": "Fixed Task B",
            "swimlaneId": "2",
            "interval": { "start": "2024-12-18", "end": "2025-01-06" }
        }
    ]
}

=== garyg1/gantt-chart-tool/docs/examples/Yarndings-20-Example.json
{
    "title": "Project a",
    "config": {
        "width": 800,
        "googleFont": "Yarndings 20",
        "startDate": "2024-11-10",
        "palette": {
            "gradient": ["#222", "#a4a4a4"],
            "backgroundColor": "#d6d6d6",
            "stripes": { "size": 6, "strength": 0.15 },
            "outlines": { "thresholdL1": 250, "strength": 0.25 }
        },
        "padding": { "swimlanes": 20 },
        "fontSizes": { "title": 22 }
    },
    "swimlanes": [
        { "id": "1", "name": "a", "maxParallelism": 3 },
        { "id": "2", "name": "b", "maxParallelism": 1 },
        { "id": "3", "name": "c", "maxParallelism": 1, "hidden": false },
        { "id": "4", "name": "d", "maxParallelism": 1 },
        { "id": "5", "name": "b", "maxParallelism": 2 }
    ],
    "tasks": [
        {
            "name": "Task 1",
            "swimlaneId": "1",
            "duration": "P20D",
            "deps": []
        },
        {
            "name": "Task 2",
            "swimlaneId": "2",
            "duration": "P11D",
            "deps": ["Task 1"]
        },
        {
            "name": "Task 3",
            "swimlaneId": "3",
            "duration": "P19D",
            "deps": ["Task 2"],
            "width": 1
        },
        {
            "name": "Task 4",
            "swimlaneId": "4",
            "duration": "P16D",
            "deps": ["Task 3"]
        },
        {
            "name": "Task 5",
            "swimlaneId": "5",
            "duration": "P17D",
            "deps": ["Task 4"]
        },
        {
            "name": "Task 6",
            "swimlaneId": "3",
            "duration": "P24D",
            "deps": ["Task 3", "Task 1"]
        },
        {
            "name": "Task 7",
            "swimlaneId": "5",
            "duration": "P22D",
            "deps": ["Task 3", "Task 6"],
            "width": 1
        },
        {
            "name": "Task 8",
            "swimlaneId": "1",
            "duration": "P23D",
            "deps": []
        },
        {
            "name": "Task 9",
            "swimlaneId": "2",
            "duration": "P12D",
            "deps": ["Task 8"]
        },
        {
            "name": "Task 10",
            "swimlaneId": "5",
            "duration": "P16D",
            "deps": ["Task 9"],
            "width": 1
        },
        {
            "name": "Task 11",
            "swimlaneId": "2",
            "duration": "P14D",
            "deps": ["Task 8"]
        },
        {
            "name": "Task 12",
            "swimlaneId": "5",
            "duration": "P24D",
            "deps": ["Task 9"],
            "width": 1
        },
        {
            "name": "Task 13",
            "swimlaneId": "5",
            "duration": "P24D",
            "deps": []
        },
        {
            "name": "Task 14",
            "swimlaneId": "5",
            "duration": "P12D",
            "deps": ["Task 13"]
        },
        {
            "name": "Fixed Task A",
            "swimlaneId": "1",
            "interval": { "start": "2024-11-15", "end": "2024-12-10" }
        },
        {
            "name": "Fixed Task B",
            "swimlaneId": "2",
            "interval": { "start": "2024-11-17", "end": "2024-12-02" }
        }
    ]
}

=== garyg1/gantt-chart-tool/docs/examples/Icon.json
{
    "title": "GCT",
    "config": {
        "width": 450,
        "googleFont": "Space Grotesk",
        "startDate": "2024-11-22",
        "dateLabels": false,
        "showDeps": true,
        "palette": {
            "gradient": ["#293936", "#477d85"],
            "backgroundColor": "#222",
            "stripes": { "size": 6, "strength": 0.15 },
            "outlines": { "thresholdL1": 210, "strength": 0.25 },
            "gridColor": ""
        },
        "padding": { "tasks": 5, "taskHeight": 15, "swimlanes": 5, "chartY": 300, "chartX": 200 },
        "fontSizes": { "taskNames": 16, "title": 74 }
    },
    "swimlanes": [
        { "id": "1", "name": "A", "maxParallelism": 2 },
        { "id": "2", "name": "B", "maxParallelism": 2 },
        { "id": "3", "name": "C", "maxParallelism": 2 }
    ],
    "tasks": [
        {
            "name": "X",
            "swimlaneId": "1",
            "duration": "PT5D",
            "deps": []
        },
        {
            "name": "Y",
            "swimlaneId": "1",
            "duration": "PT3D",
            "deps": ["X"],
            "width": 1
        },
        {
            "name": "Z",
            "swimlaneId": "2",
            "duration": "PT5D",
            "deps": ["X"]
        },
        {
            "name": "W",
            "swimlaneId": "3",
            "duration": "PT5D",
            "deps": ["Y", "Z"],
            "width": 1
        }
    ]
}

=== garyg1/gantt-chart-tool/docs/examples/Noto-Sans-Example.json
{
    "title": "スケジュール例",
    "config": {
        "width": 800,
        "googleFont": "Noto Sans",
        "startDate": "2024-11-10",
        "palette": {
            "gradient": ["#451663", "#319ee2"],
            "backgroundColor": "#dfdce9",
            "stripes": { "size": 6, "strength": 0.25 },
            "outlines": { "thresholdL1": 220, "strength": 0.25 }
        },
        "padding": { "tasks": 3, "taskHeight": 17, "swimlanes": 15 },
        "fontSizes": { "title": 16 }
    },
    "swimlanes": [
        { "id": "1", "name": "一", "maxParallelism": 3 },
        { "id": "2", "name": "二", "maxParallelism": 1 },
        { "id": "3", "name": "三", "maxParallelism": 1, "hidden": false },
        { "id": "4", "name": "四", "maxParallelism": 1 },
        { "id": "5", "name": "五", "maxParallelism": 2 }
    ],
    "tasks": [
        {
            "name": "会議の例1",
            "swimlaneId": "1",
            "duration": "PT11D",
            "deps": [],
            "width": 1
        },
        {
            "name": "会議の例2",
            "swimlaneId": "2",
            "duration": "PT15D",
            "deps": ["会議の例1"],
            "width": 1
        },
        {
            "name": "会議の例3",
            "swimlaneId": "3",
            "duration": "PT15D",
            "deps": ["会議の例2"],
            "width": 1
        },
        {
            "name": "会議の例4",
            "swimlaneId": "4",
            "duration": "PT10D",
            "deps": ["会議の例3"]
        },
        {
            "name": "会議の例5",
            "swimlaneId": "5",
            "duration": "PT21D",
            "deps": ["会議の例4"],
            "width": 1
        },
        {
            "name": "会議の例6",
            "swimlaneId": "3",
            "duration": "PT13D",
            "deps": ["会議の例5"],
            "width": 1
        },
        {
            "name": "会議の例7",
            "swimlaneId": "5",
            "duration": "PT10D",
            "deps": []
        },
        {
            "name": "会議の例8",
            "swimlaneId": "1",
            "duration": "PT11D",
            "deps": []
        },
        {
            "name": "会議の例9",
            "swimlaneId": "2",
            "duration": "PT10D",
            "deps": ["会議の例8"]
        },
        {
            "name": "会議の例10",
            "swimlaneId": "5",
            "duration": "PT16D",
            "deps": ["会議の例9"]
        },
        {
            "name": "会議の例11",
            "swimlaneId": "1",
            "duration": "PT16D",
            "deps": ["会議の例10"],
            "width": 1
        },
        {
            "name": "会議の例12",
            "swimlaneId": "5",
            "duration": "PT18D",
            "deps": ["会議の例10"]
        },
        {
            "name": "会議の例13",
            "swimlaneId": "1",
            "duration": "PT17D",
            "deps": []
        },
        {
            "name": "会議の例14",
            "swimlaneId": "1",
            "duration": "PT20D",
            "deps": ["会議の例8"],
            "width": 1
        },
        {
            "name": "修正例A",
            "swimlaneId": "1",
            "interval": { "start": "2024-11-29", "end": "2024-12-05" }
        },
        {
            "name": "修正例B",
            "swimlaneId": "2",
            "interval": { "start": "2024-12-15", "end": "2025-01-20" }
        }
    ]
}

=== garyg1/gantt-chart-tool/docs/examples/Dark-Example.json
{
    "title": "Project A",
    "config": {
        "width": 700,
        "googleFont": "Space Grotesk",
        "startDate": "2024-11-10",
        "palette": {
            "gradient": ["#293936", "#9c9c9c"],
            "backgroundColor": "#222",
            "stripes": { "size": 6 },
            "outlines": { "thresholdL1": 300, "strength": 0.25 }
        },
        "fontSizes": { "title": 34 }
    },
    "swimlanes": [
        { "id": "1", "name": "A", "maxParallelism": 2 },
        { "id": "2", "name": "B", "maxParallelism": 2 },
        { "id": "3", "name": "C", "maxParallelism": 1, "hidden": false },
        { "id": "4", "name": "D", "maxParallelism": 1 },
        { "id": "5", "name": "E", "maxParallelism": 2 }
    ],
    "tasks": [
        {
            "name": "Task 1",
            "swimlaneId": "1",
            "duration": "PT13D",
            "deps": []
        },
        {
            "name": "Task 2",
            "swimlaneId": "2",
            "duration": "PT19D",
            "deps": ["Task 1"],
            "width": 1
        },
        {
            "name": "Task 3",
            "swimlaneId": "3",
            "duration": "PT23D",
            "deps": ["Task 2"]
        },
        {
            "name": "Task 4",
            "swimlaneId": "4",
            "duration": "PT16D",
            "deps": ["Task 3"],
            "width": 1
        },
        {
            "name": "Task 5",
            "swimlaneId": "5",
            "duration": "PT10D",
            "deps": ["Task 4"]
        },
        {
            "name": "Task 6",
            "swimlaneId": "2",
            "duration": "PT22D",
            "deps": ["Task 4", "Task 3"]
        },
        {
            "name": "Task 7",
            "swimlaneId": "4",
            "duration": "PT22D",
            "deps": ["Task 4"],
            "width": 1
        },
        {
            "name": "Task 8",
            "swimlaneId": "1",
            "duration": "PT19D",
            "deps": []
        },
        {
            "name": "Task 9",
            "swimlaneId": "2",
            "duration": "PT11D",
            "deps": ["Task 8"],
            "width": 1
        },
        {
            "name": "Task 10",
            "swimlaneId": "5",
            "duration": "PT16D",
            "deps": ["Task 9"]
        },
        {
            "name": "Task 11",
            "swimlaneId": "1",
            "duration": "PT20D",
            "deps": ["Task 10"]
        },
        {
            "name": "Task 12",
            "swimlaneId": "1",
            "duration": "PT24D",
            "deps": ["Task 10"],
            "width": 1
        },
        {
            "name": "Task 13",
            "swimlaneId": "1",
            "duration": "PT14D",
            "deps": ["Task 11"]
        },
        {
            "name": "Task 14",
            "swimlaneId": "2",
            "duration": "PT12D",
            "deps": ["Task 11"],
            "width": 1
        },
        {
            "name": "Fixed Task A",
            "swimlaneId": "1",
            "interval": { "start": "2025-01-13", "end": "2025-01-29" }
        },
        {
            "name": "Fixed Task B",
            "swimlaneId": "2",
            "interval": { "start": "2025-02-08", "end": "2025-02-12" }
        }
    ]
}
