=== garyg1/gantt-chart-tool/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Gantt Chart Tool schema.",
    "type": "object",
    "properties": {
        "title": {
            "type": "string",
            "description": "Title displayed in the rendered chart."
        },
        "config": {
            "type": "object",
            "properties": {
                "dateLabels": {
                    "type": "boolean",
                    "description": "Whether to show date labels in the rendered chart."
                },
                "showDeps": {
                    "type": "boolean",
                    "description": "Whether to render lines between dependent tasks."
                },
                "width": {
                    "type": "number",
                    "description": "Width (pixels) of the rendered chart."
                },
                "font": {
                    "type": "string",
                    "description": "Font family used in the rendered chart."
                },
                "googleFont": {
                    "type": "string",
                    "description": "Google font name (https://fonts.google.com) to use in the rendered chart. Note this will trigger a request to the Google Fonts service containing the name typed here."
                },
                "palette": {
                    "type": "object",
                    "properties": {
                        "gradient": {
                            "description": "Colors the chart by a gradient between two colors. The swimlanes will be colored [gradient[0], blend1, blend2, ..., blendN, gradient[1]].",
                            "type": "array",
                            "items": {
                                "type": "string",
                                "format": "color"
                            }
                        },
                        "stripes": {
                            "description": "Options for stripes in background of rendered chart.",
                            "type": "object",
                            "properties": {
                                "size": {
                                    "type": "number",
                                    "description": "Size (in pixels) of the stripes."
                                },
                                "strength": {
                                    "type": "number",
                                    "description": "Opacity (max 1.0) of the stripes."
                                }
                            }
                        },
                        "gridColor": {
                            "type": "string",
                            "format": "color",
                            "description": "Color of the x-axis grid lines in the background."
                        }
                    },
                    "required": ["gradient"]
                },
                "startDate": {
                    "type": "string",
                    "format": "date",
                    "description": "The start date to use when auto-scheduling tasks. No task will be scheduled before this date."
                }
            },
            "required": []
        },
        "swimlanes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string",
                        "description": "A unique ID for the swimlane."
                    },
                    "name": {
                        "type": "string",
                        "description": "The displayed name of the swimlane."
                    },
                    "maxParallelism": {
                        "type": "number",
                        "description": "The maximum number of tasks that can be scheduled in parallel for this swimlane."
                    },
                    "hidden": {
                        "type": "boolean",
                        "description": "Whether to show this swimlane in the rendered chart."
                    },
                    "color": {
                        "type": "string",
                        "format": "color",
                        "description": "Overrides the color for this swimlane."
                    }
                },
                "required": ["id", "name"]
            }
        },
        "tasks": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The displayed name and key for the task"
                    },
                    "swimlaneId": {
                        "type": "string",
                        "description": "The swimlane.id for the task."
                    },
                    "duration": {
                        "type": "string",
                        "format": "duration",
                        "description": "Duration for the task, if auto-scheduled."
                    },
                    "deps": {
                        "type": "array",
                        "description": "A list of task names that must be executed before this task.",
                        "items": { "type": "string" }
                    },
                    "width": {
                        "type": "number",
                        "description": "The amount of 'bandwidth' this task takes up. For example, if `swimlane.maxParallelism = 3`, and `task.width = 3`, then this task will block the entire swimlane until it finishes executing.",
                        "default": 1
                    },
                    "interval": {
                        "type": "object",
                        "description": "The start and end times for this task, if not auto-scheduled.",
                        "properties": {
                            "start": {
                                "type": "string",
                                "format": "date"
                            },
                            "end": { "type": "string", "format": "date" }
                        },
                        "required": ["start", "end"]
                    }
                },
                "anyOf": [
                    { "required": ["interval"] },
                    { "required": ["duration"] }
                ],
                "required": ["name", "swimlaneId"]
            }
        }
    },
    "required": ["title", "config", "swimlanes", "tasks"]
}

=== garyg1/gantt-chart-tool/docs/examples/Optimality-Example.json
{
    "title": "Project A",
    "config": {
        "width": 800,
        "font": "Schibsted Grotesk",
        "startDate": "2024-11-10",
        "dateLabels": true,
        "showCriticalPaths": true,
        "palette": {
            "gradient": ["#eee", "#eee"],
            "backgroundColor": "white",
            "stripes": { "size": 6, "strength": 0.15 },
            "outlines": { "thresholdL1": 210, "strength": 0.25 }
        },
        "padding": {
            "tasks": 5,
            "taskHeight": 15,
            "swimlanes": 5,
            "chartX": 10,
            "chartY": 5
        },
        "fontSizes": { "taskNames": 12, "taskDates": 10, "title": 22 }
    },
    "swimlanes": [
        { "id": "1", "name": "A", "maxParallelism": 3 },
        { "id": "2", "name": "B", "maxParallelism": 2 },
        { "id": "3", "name": "C", "maxParallelism": 1, "hidden": false },
        { "id": "4", "name": "D", "maxParallelism": 2 },
        { "id": "5", "name": "E", "maxParallelism": 2 }
    ],
    "tasks": [
        {
            "name": "Task 1",
            "swimlaneId": "1",
            "duration": "P16D",
            "deps": []
        },
        {
            "name": "Task 2",
            "swimlaneId": "1",
            "duration": "P12D",
            "deps": ["Task 1"]
        },
        {
            "name": "Task 3",
            "swimlaneId": "1",
            "duration": "P18D",
            "deps": ["Task 2"]
        },
        {
            "name": "Task 4",
            "swimlaneId": "2",
            "duration": "P22D",
            "deps": ["Task 3"],
            "width": 1
        },
        {
            "name": "Task 5",
            "swimlaneId": "1",
            "duration": "P18D",
            "color": "black",
            "deps": []
        },
        {
            "name": "Task 6",
            "swimlaneId": "2",
            "duration": "P2W",
            "deps": ["Task 5"],
            "color": "black"
        },
        {
            "name": "Task 7",
            "swimlaneId": "3",
            "duration": "P24D",
            "deps": ["Task 6"],
            "color": "black"
        },
        {
            "name": "Task 8",
            "swimlaneId": "4",
            "duration": "P24D",
            "deps": ["Task 7"],
            "color": "black"
        },
        {
            "name": "Task 9",
            "swimlaneId": "5",
            "duration": "P17D",
            "deps": ["Task 8"],
            "color": "black"
        },
        {
            "name": "Task 10",
            "swimlaneId": "4",
            "duration": "P3W",
            "deps": ["Task 9"]
        },
        {
            "name": "Task 11",
            "swimlaneId": "5",
            "duration": "P3W",
            "deps": ["Task 9"],
            "width": 1,
            "color": "black"
        },
        {
            "name": "Task 12",
            "swimlaneId": "3",
            "duration": "P24D",
            "deps": ["Task 5"]
        },
        {
            "name": "Task 13",
            "swimlaneId": "1",
            "duration": "P10D",
            "deps": ["Task 10", "Task 11"]
        },
        {
            "name": "Task 14",
            "swimlaneId": "1",
            "duration": "P10D",
            "deps": []
        },
        {
            "name": "Task 15",
            "swimlaneId": "4",
            "duration": "P11D",
            "deps": ["Task 9"],
            "width": 1
        },
        {
            "name": "Task 16",
            "swimlaneId": "1",
            "duration": "P22D",
            "deps": ["Task 8", "Task 6"]
        },
        {
            "name": "Task 17",
            "swimlaneId": "5",
            "duration": "P20D",
            "deps": ["Task 6"]
        },
        {
            "name": "Task 18",
            "swimlaneId": "2",
            "duration": "P17D",
            "deps": ["Task 13"],
            "width": 1
        },
        {
            "name": "Task 19",
            "swimlaneId": "1",
            "duration": "P17D",
            "deps": []
        },
        {
            "name": "Task 20",
            "swimlaneId": "1",
            "duration": "P2W",
            "deps": ["Task 16", "Task 7"]
        },
        {
            "name": "Task 21",
            "swimlaneId": "4",
            "duration": "P16D",
            "deps": ["Task 5"]
        },
        {
            "name": "Task 22",
            "swimlaneId": "4",
            "duration": "P24D",
            "deps": ["Task 6"]
        },
        {
            "name": "Task 23",
            "swimlaneId": "4",
            "duration": "P24D",
            "deps": ["Task 5"]
        },
        {
            "name": "Task 24",
            "swimlaneId": "1",
            "duration": "P17D",
            "deps": ["Task 11"],
            "color": "black"
        },
        {
            "name": "Task 25",
            "swimlaneId": "5",
            "duration": "P11D",
            "deps": ["Task 23"]
        },
        {
            "name": "Task 26",
            "swimlaneId": "4",
            "duration": "P15D",
            "deps": []
        },
        {
            "name": "Task 27",
            "swimlaneId": "4",
            "duration": "P24D",
            "deps": ["Task 24", "Task 19"],
            "color": "black"
        },
        {
            "name": "Task 28",
            "swimlaneId": "4",
            "duration": "P20D",
            "deps": ["Task 14"]
        },
        {
            "name": "Task 29",
            "swimlaneId": "1",
            "duration": "P22D",
            "deps": ["Task 13"]
        },
        {
            "name": "Task 30",
            "swimlaneId": "4",
            "duration": "P22D",
            "deps": ["Task 7"]
        },
        {
            "name": "Task 31",
            "swimlaneId": "3",
            "duration": "P13D",
            "deps": ["Task 30"]
        },
        {
            "name": "Task 32",
            "swimlaneId": "2",
            "duration": "P17D",
            "deps": ["Task 12", "Task 8"]
        },
        {
            "name": "Task 33",
            "swimlaneId": "5",
            "duration": "P3W",
            "deps": ["Task 27", "Task 11"],
            "color": "black"
        },
        {
            "name": "Task 34",
            "swimlaneId": "4",
            "duration": "P13D",
            "deps": ["Task 33", "Task 18"],
            "color": "black"
        },
        {
            "name": "Fixed Task A",
            "swimlaneId": "1",
            "interval": { "start": "2024-12-19", "end": "2024-12-25" }
        },
        {
            "name": "Fixed Task B",
            "swimlaneId": "2",
            "interval": { "start": "2025-02-03", "end": "2025-03-10" }
        }
    ]
}
